# Generated by Django 5.2 on 2025-12-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('query', models.CharField(db_index=True, help_text='The search query', max_length=500)),
                ('results_count', models.IntegerField(default=0, help_text='Number of results returned')),
                ('filters_used', models.JSONField(blank=True, default=dict, help_text='Filters applied to the search')),
                ('clicked_result_id', models.PositiveIntegerField(blank=True, help_text='ID of result that was clicked', null=True)),
                ('clicked_result_type', models.CharField(blank=True, default='', help_text='Model type of clicked result', max_length=100)),
                ('search_duration_ms', models.IntegerField(blank=True, help_text='Search execution time in milliseconds', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Search histories',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='search_sear_user_id_677f6a_idx'), models.Index(fields=['query'], name='search_sear_query_d8a8e0_idx')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(db_index=True, help_text='Primary searchable title', max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Secondary text (description, summary)', max_length=500)),
                ('content', models.TextField(blank=True, default='', help_text='Full text content for search')),
                ('keywords', models.TextField(blank=True, default='', help_text='Additional keywords for search')),
                ('model_name', models.CharField(db_index=True, help_text='Name of the source model', max_length=100)),
                ('model_verbose_name', models.CharField(blank=True, default='', max_length=100)),
                ('icon', models.CharField(default='file', help_text='Icon for display in search results', max_length=50)),
                ('url', models.CharField(blank=True, default='', help_text='URL to the object', max_length=500)),
                ('visibility', models.CharField(db_index=True, default='private', help_text='Visibility level from source object', max_length=20)),
                ('owner_id', models.PositiveIntegerField(blank=True, db_index=True, help_text='Owner user ID for access control', null=True)),
                ('weight', models.IntegerField(db_index=True, default=1, help_text='Weight for ranking (higher = more relevant)')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Additional data for display')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Search Index Entry',
                'verbose_name_plural': 'Search Index Entries',
                'indexes': [models.Index(fields=['title'], name='search_sear_title_51a3a1_idx'), models.Index(fields=['model_name', 'visibility'], name='search_sear_model_n_057b8b_idx'), models.Index(fields=['owner_id', 'visibility'], name='search_sear_owner_i_ae28a9_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
