# Generated by Django 5.2 on 2025-12-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Landing FAQ',
                'verbose_name_plural': 'Landing FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('lightning', 'Lightning Bolt'), ('grid', 'Grid/Dashboard'), ('shield', 'Shield'), ('clock', 'Clock'), ('cube', 'Cube/3D'), ('chart', 'Chart'), ('users', 'Users'), ('document', 'Document')], default='shield', max_length=20)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'Landing Feature',
                'verbose_name_plural': 'Landing Features',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_badge_text', models.CharField(default='Next Gen Insurance', help_text='Badge text above the title', max_length=50)),
                ('hero_title', models.CharField(default='Insurance Simplified for Modern Business', max_length=200)),
                ('hero_subtitle', models.TextField(default='Experience lightning-fast claims, transparent policies, and specific coverage tailored for your growth. No paperwork, just protection.')),
                ('hero_cta_primary_text', models.CharField(default='Start Free Trial', max_length=50)),
                ('hero_cta_secondary_text', models.CharField(default='Learn More', max_length=50)),
                ('hero_feature_1', models.CharField(default='Instant Approval', max_length=50)),
                ('hero_feature_2', models.CharField(default='24/7 Support', max_length=50)),
                ('demo_coverage_amount', models.CharField(default='KES 50,000,000', max_length=50)),
                ('demo_growth_percentage', models.CharField(default='+12.5%', max_length=20)),
                ('demo_policies_count', models.CharField(default='1,234', max_length=20)),
                ('demo_claims_rate', models.CharField(default='98%', max_length=20)),
                ('trusted_by_text', models.CharField(default='Trusted by over 2,000 modern companies', max_length=100)),
                ('features_title', models.CharField(default='Why Choose ifinsure?', max_length=100)),
                ('features_subtitle', models.TextField(default="We've reimagined insurance from the ground up to serve the speed of modern business.")),
                ('process_title', models.CharField(default='Insurance in 3 Simple Steps', max_length=100)),
                ('process_step_1_title', models.CharField(default='Apply Online', max_length=50)),
                ('process_step_1_description', models.TextField(default='Fill out a simple, smart form to tell us about your business needs in under 5 minutes.')),
                ('process_step_2_title', models.CharField(default='Get Approved', max_length=50)),
                ('process_step_2_description', models.TextField(default='Our AI reviews your application instantly, generating a custom quote and immediate coverage.')),
                ('process_step_3_title', models.CharField(default='Manage Policy', max_length=50)),
                ('process_step_3_description', models.TextField(default='Access your state-of-the-art dashboard to file claims, adjust coverage, and pay premiums 24/7.')),
                ('testimonials_title', models.CharField(default='Loved by Businesses Everywhere', max_length=100)),
                ('testimonials_subtitle', models.TextField(default='See what our customers have to say about their experience with ifinsure.')),
                ('faq_title', models.CharField(default='Frequently Asked Questions', max_length=100)),
                ('faq_subtitle', models.TextField(default='Everything you need to know about ifinsure.')),
                ('cta_title', models.CharField(default='Ready to secure your future?', max_length=100)),
                ('cta_subtitle', models.TextField(default='Join thousands of businesses trusting ifinsure today.')),
                ('cta_button_text', models.CharField(default='Get Started', max_length=50)),
                ('cta_disclaimer', models.CharField(default='No credit card required. Start your free trial today.', max_length=200)),
                ('floating_cta_text', models.CharField(default='Get Protected', max_length=50)),
            ],
            options={
                'verbose_name': 'Landing Page Settings',
                'verbose_name_plural': 'Landing Page Settings',
            },
        ),
        migrations.CreateModel(
            name='LandingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('value', models.CharField(help_text="e.g., '2M+', '98%', '24/7'", max_length=20)),
                ('label', models.CharField(help_text="e.g., 'Active Policies'", max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_animated', models.BooleanField(default=True)),
                ('numeric_value', models.IntegerField(blank=True, help_text="Numeric value for animation (e.g., 2 for '2M+')", null=True)),
                ('suffix', models.CharField(blank=True, help_text="Suffix for animation (e.g., 'M+', '%')", max_length=10)),
            ],
            options={
                'verbose_name': 'Landing Statistic',
                'verbose_name_plural': 'Landing Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LandingTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('quote', models.TextField()),
                ('author_name', models.CharField(max_length=100)),
                ('author_title', models.CharField(help_text="e.g., 'CEO, TechCorp'", max_length=100)),
                ('author_initials', models.CharField(help_text="Initials for avatar (e.g., 'JM')", max_length=3)),
                ('rating', models.PositiveIntegerField(default=5, help_text='Star rating (1-5)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Landing Testimonial',
                'verbose_name_plural': 'Landing Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LandingTrustedCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('name', models.CharField(max_length=100)),
                ('svg_code', models.TextField(blank=True, help_text='SVG code for the company logo')),
                ('logo_url', models.URLField(blank=True, help_text='URL to logo image (alternative to SVG)')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Trusted Company',
                'verbose_name_plural': 'Trusted Companies',
                'ordering': ['order'],
            },
        ),
    ]
