# Generated by Django 5.2 on 2025-12-25 11:27

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_reviews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Audit Log', 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_user_id_7b678c_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='core_auditl_action_096de0_idx',
        ),
        migrations.RemoveField(
            model_name='auditlog',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='auditlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='landingpagesettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'created_at'], name='core_auditl_user_id_413764_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action', 'created_at'], name='core_auditl_action_29a2bf_idx'),
        ),
    ]
