# Generated by Django 5.2 on 2025-12-24 21:27

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('daily_capacity', models.PositiveIntegerField(default=15, help_text='Maximum tickets this agent can handle per day')),
                ('current_load', models.PositiveIntegerField(default=0, help_text='Current active tickets')),
                ('is_available', models.BooleanField(default=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning (6AM - 2PM)'), ('afternoon', 'Afternoon (2PM - 10PM)'), ('night', 'Night (10PM - 6AM)'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('shift_start', models.TimeField(blank=True, null=True)),
                ('shift_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='workflow.agentprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='workflow.department')),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(db_index=True, max_length=30, unique=True)),
                ('ticket_type', models.CharField(choices=[('claim', 'Claim'), ('policy', 'Policy'), ('billing', 'Billing'), ('inquiry', 'General Inquiry'), ('complaint', 'Complaint'), ('renewal', 'Renewal'), ('endorsement', 'Endorsement')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('pending_customer', 'Pending Customer'), ('pending_approval', 'Pending Approval'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('required_workclass_level', models.PositiveIntegerField(default=2, help_text='Minimum workclass level required')),
                ('estimated_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated monetary value (for determining required level)', max_digits=15)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('first_response_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('escalation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='workflow.agentprofile')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_tickets', to=settings.AUTH_USER_MODEL)),
                ('escalated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='workflow.ticket')),
                ('required_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='workflow.department')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('created', 'Created'), ('assigned', 'Assigned'), ('picked', 'Picked'), ('status_change', 'Status Changed'), ('note', 'Note Added'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('reopened', 'Reopened')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='workflow.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Activity',
                'verbose_name_plural': 'Ticket Activities',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkClass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('level', models.PositiveIntegerField(choices=[(1, 'Level 1 - Trainee'), (2, 'Level 2 - Junior Agent'), (3, 'Level 3 - Agent'), (4, 'Level 4 - Senior Agent'), (5, 'Level 5 - Supervisor/Admin')], default=2)),
                ('description', models.TextField(blank=True)),
                ('monetary_limit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum amount this workclass can approve', max_digits=15)),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Detailed permission flags')),
                ('daily_ticket_limit', models.PositiveIntegerField(default=20, help_text='Maximum tickets per day for agents in this class')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workclasses', to='workflow.department')),
            ],
            options={
                'verbose_name': 'Work Class',
                'verbose_name_plural': 'Work Classes',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='primary_workclass',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_agents', to='workflow.workclass'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='workclasses',
            field=models.ManyToManyField(blank=True, related_name='agents', to='workflow.workclass'),
        ),
        migrations.CreateModel(
            name='AgentPerformance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('tickets_assigned', models.PositiveIntegerField(default=0)),
                ('tickets_resolved', models.PositiveIntegerField(default=0)),
                ('tickets_escalated', models.PositiveIntegerField(default=0)),
                ('tickets_reopened', models.PositiveIntegerField(default=0)),
                ('avg_resolution_time', models.PositiveIntegerField(default=0)),
                ('avg_first_response_time', models.PositiveIntegerField(default=0)),
                ('total_work_time', models.PositiveIntegerField(default=0)),
                ('sla_met', models.PositiveIntegerField(default=0)),
                ('sla_breached', models.PositiveIntegerField(default=0)),
                ('policies_sold', models.PositiveIntegerField(default=0)),
                ('total_premium_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('leads_handled', models.PositiveIntegerField(default=0)),
                ('leads_converted', models.PositiveIntegerField(default=0)),
                ('claims_approved', models.PositiveIntegerField(default=0)),
                ('claims_rejected', models.PositiveIntegerField(default=0)),
                ('total_claims_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('csat_responses', models.PositiveIntegerField(default=0)),
                ('csat_total_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='workflow.agentprofile')),
            ],
            options={
                'verbose_name': 'Agent Performance',
                'verbose_name_plural': 'Agent Performance Records',
                'ordering': ['-period_start'],
                'unique_together': {('agent', 'period_type', 'period_start')},
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', '-created_at'], name='workflow_ti_status_690375_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['assigned_to', 'status'], name='workflow_ti_assigne_46bafa_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['ticket_type', 'status'], name='workflow_ti_ticket__1866f5_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['reference'], name='workflow_ti_referen_05a22c_idx'),
        ),
    ]
