# Generated by Django 5.2 on 2025-12-25 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentperformance',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='ticketactivity',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='agentperformance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='ticketactivity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AlterField(
            model_name='workclass',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
    ]
