# Generated by Django 5.2 on 2025-12-25 06:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceproduct',
            name='allow_partial_payment',
            field=models.BooleanField(default=False, help_text='Allow customers to pay in installments after approval'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='application_payment_mode',
            field=models.CharField(choices=[('none', 'No Payment Required'), ('convenience_only', 'Convenience Fee Only'), ('full', 'Full Payment (Fee + Premium)')], default='convenience_only', help_text='Payment required when submitting application', max_length=20),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='convenience_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='Application/Processing fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='convenience_fee_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Premium')], default='fixed', help_text='How convenience fee is calculated', max_length=20),
        ),
    ]
