# Generated by Django 5.2 on 2025-12-25 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_insuranceproduct_allow_partial_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerdocument',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='customertag',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='customerdocument',
            name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='notes',
        ),
        migrations.AddField(
            model_name='communication',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='communication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customertag',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productcategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='providercontact',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AlterField(
            model_name='insuranceproduct',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
    ]
