# Generated by Django 5.2 on 2025-12-25 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0003_alter_customerdocument_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='communication',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='communication',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='communication',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='communication',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='communication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='communication',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='communication',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='communication',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customer',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='customer',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='customer',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='customer',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='customertag',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='customertag',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customertag',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='customertag',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='features',
            field=models.JSONField(blank=True, default=list, help_text='List of product features'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='max_term_months',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='min_term_months',
            field=models.PositiveIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='insuranceproduct',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='insuranceprovider',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='lead',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='lead',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='lead',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='lead',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lead',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='productbenefit',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='providercontact',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lead',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
