# Generated by Django 5.2 on 2025-12-26 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrashRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('object_id', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(help_text='Display title of the trashed item', max_length=500)),
                ('subtitle', models.CharField(blank=True, default='', help_text='Additional info about the item', max_length=500)),
                ('icon', models.CharField(default='file', help_text='Icon for display', max_length=50)),
                ('model_name', models.CharField(db_index=True, help_text='Name of the source model', max_length=100)),
                ('model_verbose_name', models.CharField(blank=True, default='', max_length=100)),
                ('trash_reason', models.TextField(blank=True, default='', help_text='Reason for trashing')),
                ('original_data', models.JSONField(blank=True, default=dict, help_text='Backup of important data before trashing')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this item will be permanently deleted')),
                ('restore_url', models.CharField(blank=True, default='', help_text='URL for restoring this item', max_length=500)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('trashed_by', models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trashed_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trash Item',
                'verbose_name_plural': 'Trash Items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['trashed_by', 'created_at'], name='trash_trash_trashed_15570e_idx'), models.Index(fields=['model_name'], name='trash_trash_model_n_6a1ebf_idx'), models.Index(fields=['expires_at'], name='trash_trash_expires_d7da11_idx')],
                'unique_together': {('content_type', 'object_id')},
            },
        ),
    ]
