# Generated by Django 5.2 on 2025-12-26 15:30

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('trashed_at', models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True)),
                ('permanent_delete_at', models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True)),
                ('trash_reason', models.TextField(blank=True, default='', help_text='Reason for trashing this item')),
                ('visibility', models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this resource was published', null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Whether user consented to data processing')),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='When consent was given', null=True)),
                ('is_anonymized', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized')),
                ('anonymized_at', models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True)),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('currency', models.CharField(choices=[('KES', 'Kenyan Shilling'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound')], default='KES', max_length=3)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('trashed_by', models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('trashed_at', models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True)),
                ('permanent_delete_at', models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True)),
                ('trash_reason', models.TextField(blank=True, default='', help_text='Reason for trashing this item')),
                ('visibility', models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20)),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published')),
                ('published_at', models.DateTimeField(blank=True, help_text='When this resource was published', null=True)),
                ('consent_given', models.BooleanField(default=False, help_text='Whether user consented to data processing')),
                ('consent_given_at', models.DateTimeField(blank=True, help_text='When consent was given', null=True)),
                ('is_anonymized', models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized')),
                ('anonymized_at', models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True)),
                ('retain_until', models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True)),
                ('notifications_enabled', models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource')),
                ('last_notified_at', models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('payment', 'Payment'), ('refund', 'Refund'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('premium_payment', 'Premium Payment'), ('claim_payout', 'Claim Payout'), ('adjustment', 'Adjustment')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='completed', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('allowed_groups', models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL)),
                ('trashed_by', models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
                ('watchers', models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['wallet', '-created_at'], name='wallets_wal_wallet__ed7753_idx'), models.Index(fields=['reference'], name='wallets_wal_referen_41fe73_idx'), models.Index(fields=['transaction_type'], name='wallets_wal_transac_448a4d_idx')],
            },
        ),
    ]
