# Generated by Django 5.2 on 2025-12-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp'),
        ),
    ]
