# Generated by Django 5.2 on 2025-12-25 11:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='claimstatushistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Status History', 'verbose_name_plural': 'Status Histories'},
        ),
        migrations.RemoveField(
            model_name='claimstatushistory',
            name='changed_at',
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default='2025-12-25T11:27:00+00:00', help_text='Record creation timestamp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted'),
        ),
        migrations.AddField(
            model_name='claimstatushistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Record last update timestamp'),
        ),
    ]
