# Generated by Django 5.2.9 on 2025-12-23 19:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('category', models.CharField(choices=[('life', 'Life Insurance'), ('health', 'Health Insurance'), ('auto', 'Auto Insurance'), ('home', 'Home Insurance'), ('business', 'Business Insurance'), ('travel', 'Travel Insurance')], db_index=True, max_length=20)),
                ('description', models.TextField()),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('base_premium', models.DecimalField(decimal_places=2, help_text='Base premium amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_coverage', models.DecimalField(decimal_places=2, default=Decimal('100000.00'), help_text='Minimum coverage amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('max_coverage', models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), help_text='Maximum coverage amount', max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('min_term_months', models.PositiveIntegerField(default=12)),
                ('max_term_months', models.PositiveIntegerField(default=120)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list, help_text='List of product features')),
            ],
            options={
                'verbose_name': 'Insurance Product',
                'verbose_name_plural': 'Insurance Products',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('policy_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Activation'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('lapsed', 'Lapsed')], db_index=True, default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('coverage_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=100)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_policies', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(limit_choices_to={'user_type': 'customer'}, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='policies.insuranceproduct')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('application_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('requested_coverage', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('requested_term_months', models.PositiveIntegerField(default=12)),
                ('payment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='monthly', max_length=20)),
                ('calculated_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('beneficiary_name', models.CharField(blank=True, max_length=200)),
                ('beneficiary_relationship', models.CharField(blank=True, max_length=100)),
                ('beneficiary_phone', models.CharField(blank=True, max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('assigned_agent', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'agent'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('policy', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='policies.policy')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='policies.insuranceproduct')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Policy Application',
                'verbose_name_plural': 'Policy Applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PolicyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('document_type', models.CharField(choices=[('certificate', 'Policy Certificate'), ('terms', 'Terms & Conditions'), ('endorsement', 'Endorsement'), ('renewal', 'Renewal Notice'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='policies/documents/%Y/%m/')),
                ('description', models.TextField(blank=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='policies.policy')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['customer', 'status'], name='policies_po_custome_ec5ded_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['policy_number'], name='policies_po_policy__a03f9f_idx'),
        ),
        migrations.AddIndex(
            model_name='policy',
            index=models.Index(fields=['agent', 'status'], name='policies_po_agent_i_30c42b_idx'),
        ),
        migrations.AddIndex(
            model_name='policyapplication',
            index=models.Index(fields=['applicant', 'status'], name='policies_po_applica_db9f1e_idx'),
        ),
        migrations.AddIndex(
            model_name='policyapplication',
            index=models.Index(fields=['application_number'], name='policies_po_applica_268e41_idx'),
        ),
    ]
