# Generated by Django 5.2 on 2025-12-25 06:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyapplication',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=12),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='convenience_fee_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Application convenience fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Reference from payment system', max_length=100),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='payment_status',
            field=models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='premium_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Premium amount required at application', max_digits=12),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='total_payment_due',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total payment required', max_digits=12),
        ),
    ]
