# Generated by Django 5.2 on 2025-12-25 17:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('crm', '0004_communication_allowed_groups_and_more'),
        ('policies', '0002_policyapplication_amount_paid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyapplication',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='crm.insuranceproduct'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='crm.insuranceproduct'),
        ),
        migrations.RemoveField(
            model_name='policydocument',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='policy',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='policy',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='policy',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='policy',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='policy',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='policy',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policy',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='policy',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='policyapplication',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, help_text='Groups who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, help_text='Users who can access this resource when restricted', related_name='%(app_label)s_%(class)s_allowed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='anonymized_at',
            field=models.DateTimeField(blank=True, help_text='When this record was anonymized', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='consent_given',
            field=models.BooleanField(default=False, help_text='Whether user consented to data processing'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text='When consent was given', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='is_anonymized',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this record has been anonymized'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, help_text='Whether this resource is published'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='last_notified_at',
            field=models.DateTimeField(blank=True, help_text='When the last notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='modified_by',
            field=models.ForeignKey(blank=True, help_text='User who last modified this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modified', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='notifications_enabled',
            field=models.BooleanField(default=True, help_text='Whether notifications are enabled for this resource'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Owner of this resource', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_owned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='permanent_delete_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item will be permanently deleted', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='published_at',
            field=models.DateTimeField(blank=True, help_text='When this resource was published', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='retain_until',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date until which this record must be retained', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='trash_reason',
            field=models.TextField(blank=True, default='', help_text='Reason for trashing this item'),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='trashed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When this item was moved to trash', null=True),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='trashed_by',
            field=models.ForeignKey(blank=True, help_text='User who trashed this item', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_trashed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public - Visible to everyone'), ('private', 'Private - Visible to owner only'), ('internal', 'Internal - Visible to staff'), ('restricted', 'Restricted - Visible to specific users/groups')], db_index=True, default='private', help_text='Who can see this resource', max_length=20),
        ),
        migrations.AddField(
            model_name='policydocument',
            name='watchers',
            field=models.ManyToManyField(blank=True, help_text='Users watching this resource for changes', related_name='%(app_label)s_%(class)s_watching', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='policyapplication',
            name='application_number',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name='InsuranceProduct',
        ),
    ]
