# Generated by Django 5.2 on 2025-12-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('email_enabled', models.BooleanField(default=True, help_text='Receive email notifications')),
                ('sms_enabled', models.BooleanField(default=False, help_text='Receive SMS notifications')),
                ('push_enabled', models.BooleanField(default=True, help_text='Receive push notifications')),
                ('in_app_enabled', models.BooleanField(default=True, help_text='Receive in-app notifications')),
                ('notify_policy_created', models.BooleanField(default=True)),
                ('notify_policy_updated', models.BooleanField(default=True)),
                ('notify_policy_expiring', models.BooleanField(default=True)),
                ('notify_policy_expired', models.BooleanField(default=True)),
                ('notify_claim_submitted', models.BooleanField(default=True)),
                ('notify_claim_updated', models.BooleanField(default=True)),
                ('notify_claim_approved', models.BooleanField(default=True)),
                ('notify_claim_rejected', models.BooleanField(default=True)),
                ('notify_payment_due', models.BooleanField(default=True)),
                ('notify_payment_received', models.BooleanField(default=True)),
                ('notify_payment_overdue', models.BooleanField(default=True)),
                ('notify_system_updates', models.BooleanField(default=True)),
                ('notify_security_alerts', models.BooleanField(default=True)),
                ('notify_promotions', models.BooleanField(default=False)),
                ('quiet_hours_enabled', models.BooleanField(default=False, help_text='Enable quiet hours (no notifications during specified time)')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (e.g., 22:00)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours (e.g., 07:00)', null=True)),
                ('email_digest_enabled', models.BooleanField(default=False, help_text='Receive email digest instead of individual emails')),
                ('email_digest_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='daily', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Record last update timestamp')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Soft delete flag - False means deleted')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('action', 'Action Required')], db_index=True, default='info', max_length=20)),
                ('channel', models.CharField(choices=[('in_app', 'In-App'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], db_index=True, default='in_app', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('icon', models.CharField(default='bell', help_text='Icon name for display', max_length=50)),
                ('icon_color', models.CharField(blank=True, default='', help_text='Icon color class', max_length=20)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('action_url', models.CharField(blank=True, default='', help_text='URL to navigate to when notification is clicked', max_length=500)),
                ('is_read', models.BooleanField(db_index=True, default=False, help_text='Whether the notification has been read')),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Whether the notification is archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_error', models.TextField(blank=True, default='')),
                ('priority', models.IntegerField(db_index=True, default=0, help_text='Higher priority notifications appear first')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification expires and disappears after this time', null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(help_text='User who receives this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', 'is_archived'], name='notificatio_recipie_4f5d40_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_702c56_idx')],
            },
        ),
    ]
